# Generated by Django 5.2.8 on 2025-11-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_core", "0002_costcenter_remove_journalentry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="current_balance_from_statement",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=18),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="balance",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=18),
        ),
    ]
