# Generated by Django 5.2.8 on 2025-11-23 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "email_personal",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "email_official",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone_personal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "phone_official",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                ("identifications", models.JSONField(default=dict)),
                ("photo_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("TERMINATED", "Terminated"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("date_joined", models.DateField()),
                ("date_confirmed", models.DateField(blank=True, null=True)),
                ("date_terminated", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompensationStructureMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("structure_code", models.CharField(max_length=50)),
                ("grade", models.CharField(max_length=50)),
                ("ctc_band", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=10)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_core.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("action_type", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("payload_before", models.JSONField()),
                ("payload_after", models.JSONField()),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_core.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationalUnit",
            fields=[
                (
                    "org_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_units",
                        to="people_core.employee",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="people_core.organizationalunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "position_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("job_code", models.CharField(max_length=50)),
                ("grade", models.CharField(max_length=50)),
                ("vacancy_status", models.CharField(max_length=50)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="people_core.organizationalunit",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="people_core.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("job_code", models.CharField(max_length=50)),
                ("grade", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                ("employee_type", models.CharField(max_length=100)),
                ("employment_type", models.CharField(max_length=100)),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("work_location", models.CharField(max_length=255)),
                ("work_country", models.CharField(max_length=100)),
                ("remote_status", models.CharField(max_length=50)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("cost_center", models.CharField(max_length=100)),
                ("is_primary", models.BooleanField(default=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people_core.employee",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisees",
                        to="people_core.employee",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="people_core.organizationalunit",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="people_core.position",
                    ),
                ),
            ],
        ),
    ]
