# Generated by Django 5.2.8 on 2025-11-23 12:03

from django.db import migrations
from datetime import date

def create_seed_data(apps, schema_editor):
    Employee = apps.get_model('people_core', 'Employee')
    OrganizationalUnit = apps.get_model('people_core', 'OrganizationalUnit')
    Position = apps.get_model('people_core', 'Position')

    # Create Org Units
    company = OrganizationalUnit.objects.create(name='ARCA Global', code='ARCA', type='Company', start_date=date(2020, 1, 1))
    hr_dept = OrganizationalUnit.objects.create(name='Human Resources', code='HR', type='Department', parent=company, start_date=date(2020, 1, 1))
    eng_dept = OrganizationalUnit.objects.create(name='Engineering', code='ENG', type='Department', parent=company, start_date=date(2020, 1, 1))

    # Create Positions
    hr_manager_pos = Position.objects.create(title='HR Manager', job_code='HRM', grade='M1', department=hr_dept, vacancy_status='Filled')
    swe_pos = Position.objects.create(title='Software Engineer', job_code='SWE', grade='E1', department=eng_dept, vacancy_status='Open')

    # Create Employees
    Employee.objects.create(first_name='John', last_name='Doe', email_official='john.doe@arca.com', date_joined=date(2021, 1, 15))
    Employee.objects.create(first_name='Jane', last_name='Smith', email_official='jane.smith@arca.com', date_joined=date(2022, 3, 1))

class Migration(migrations.Migration):

    dependencies = [
        ('people_core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_seed_data),
    ]
