# Generated by Django 5.2.8 on 2025-11-20 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org_core", "0001_initial"),
        ("people_ops", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="org_core.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="employee",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="org_core.position",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("On Leave", "On Leave"),
                    ("Terminated", "Terminated"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
